fastlane_version "1.51.0"

platform :ios do

  ############################## PRE ##############################

  before_all do

    ensure_git_status_clean
    cocoapods

  end

  ######################### PUBLIC LANES ##########################

  lane :test do
    scan(
      scheme: "FootballCollegeTrivia",
      clean: true,
      destination: "platform=iOS Simulator,name=iPhone 6,OS=9.2"
    )
  end

  lane :screens do
    snapshot(
      scheme: "FootballCollegeTrivia",
      clear_previous_screenshots: true,
      clean: true,
      devices: [
        "iPhone 6",
        "iPhone 6 Plus",
        "iPhone 5",
        "iPhone 4s",
      ]
    )
  end

  ############################# POST ##############################

  after_all do |lane|

  end

  error do |lane, exception|
    notification(message:"fastlane finished '#{lane}'") # Mac OS X Notification
  end

end
