fastlane_version "1.66.0"

platform :ios do

  ############################## PRE ##############################

  before_all do

    #ensure_git_status_clean
    cocoapods

  end

  ######################### PUBLIC LANES ##########################

  lane :test do

    scan(
      scheme: "FootballCollegeTrivia",
      clean: true,
      destination: "platform=iOS Simulator,name=iPhone 6,OS=9.2"
    )

  end

  lane :screens do

    snapshot(
      scheme: "FootballCollegeTrivia",
      clear_previous_screenshots: true,
      clean: true,
      devices: [
        "iPad Pro",
        "iPhone 6 Plus",
        "iPhone 6",
        "iPhone 5s",
        "iPhone 4s",
      ]
    )

  end

  lane :fabric do

    gym(
      scheme: "FootballCollegeTrivia",
      use_legacy_build_api: true,
      codesigning_identity: "iPhone Developer: Brandon Jenniges" #force use of developer codesigning (change to user specific identity if different)
    )

    git_message = sh("git log --pretty=format:\"%h - %an, %s\" -10")

    crashlytics(
      crashlytics_path: './Crashlytics.framework',
      ipa_path: './FootballCollegeTrivia.ipa',    
      notes: "Recent commits \n ---------- \n #{git_message.to_s}",
      groups: ["ios-test"], #alias name not group name
      notifications: false,
    )

  end

  lane :testflight do 

    gym(scheme: "FootballCollegeTrivia")

    pilot()

  end

  ############################# POST ##############################

  after_all do |lane|

  end

  error do |lane, exception|
    notification(message:"fastlane finished '#{lane}'") # Mac OS X Notification
  end

end
