# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 6",
   "iPhone 6 Plus",
   "iPhone 5",
   "iPhone 4s",
#   "iPad Retina",
#   "iPad Pro"
 ])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
 scheme "FootballCollegeTrivia"


# clear_previous_screenshots # remove the '#' to clear all previously generated screenshots before creating new ones

